import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const cfg = window.IGCSEMYSG_CONFIG || {};
const configured = Boolean(cfg.supabaseUrl && cfg.supabaseAnonKey);
const supabase = configured ? createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
const $ = (q) => document.querySelector(q);
const state = { user:null, demo:false, view:"dashboard", board:"Cambridge IGCSE", subject:"Mathematics", progress:[], messages:[], conversationId:null, preferences:{multi_model_mode:false} };

const curriculum = {
  Mathematics:[
    {id:"alg",title:"Algebra & functions",level:"Core skill",summary:"Expressions, equations, inequalities and function notation.",progress:72},
    {id:"geo",title:"Geometry & measure",level:"Exam focus",summary:"Angle reasoning, similarity, mensuration and transformations.",progress:48},
    {id:"trig",title:"Trigonometry",level:"Priority",summary:"Right-angle methods, sine and cosine rules, bearings and graphs.",progress:31},
    {id:"stat",title:"Statistics & probability",level:"Core skill",summary:"Representing data, probability models and interpretation.",progress:64},
    {id:"num",title:"Number",level:"Foundation",summary:"Accuracy, bounds, ratio, proportion and standard form.",progress:81},
    {id:"vec",title:"Vectors",level:"High difficulty",summary:"Vector geometry, ratios and proof.",progress:25}
  ],
  Physics:[
    {id:"motion",title:"Motion, forces & energy",level:"Priority",summary:"Kinematics, dynamics, work, energy and power.",progress:46},
    {id:"thermal",title:"Thermal physics",level:"Core skill",summary:"Particle model, heat capacity and transfer.",progress:63},
    {id:"waves",title:"Waves",level:"Exam focus",summary:"Wave properties, light, sound and the EM spectrum.",progress:38},
    {id:"electric",title:"Electricity",level:"High difficulty",summary:"Circuits, resistance, power and electrical safety.",progress:29},
    {id:"atomic",title:"Atomic physics",level:"Core skill",summary:"Radioactivity, decay and nuclear structure.",progress:54}
  ]
};
const defaultTopics = curriculum.Mathematics;
const questions = [
  {topic:"Algebra & functions",prompt:"If f(x) = 3x − 5, find f⁻¹(x).",choices:["(x + 5) / 3","3x + 5","(x − 5) / 3","5 − 3x"],answer:0,why:"Reverse the operations: add 5, then divide by 3."},
  {topic:"Trigonometry",prompt:"A right triangle has opposite side 8 cm and hypotenuse 10 cm. Find sin θ.",choices:["0.6","0.8","1.25","18"],answer:1,why:"sin θ = opposite ÷ hypotenuse = 8 ÷ 10 = 0.8."},
  {topic:"Vectors",prompt:"If a = (2, 3) and b = (−1, 4), what is a + b?",choices:["(1, 7)","(3, −1)","(−2, 12)","(1, 1)"],answer:0,why:"Add corresponding components: (2 − 1, 3 + 4) = (1, 7)."}
];

async function init(){
  bind();
  if(supabase){ const {data}=await supabase.auth.getSession(); if(data.session) await enter(data.session.user); supabase.auth.onAuthStateChange((_e,s)=>s?.user?enter(s.user):showAuth()); }
  const demo=localStorage.getItem("igcsemysg_demo")==="1"; if(!state.user&&demo){state.demo=true;state.user={email:"demo@student.local",id:"demo"};loadLocal();showApp();}
}
function bind(){
  let signup=false;
  $("#auth-switch").onclick=()=>{signup=!signup;$("#auth-title").textContent=signup?"Create your account":"Welcome back";$("#auth-submit").textContent=signup?"Create account":"Sign in";$("#auth-switch").textContent=signup?"Already registered? Sign in":"New student? Create an account";};
  $("#auth-form").onsubmit=async e=>{e.preventDefault();$("#auth-error").textContent="";if(!supabase){$("#auth-error").textContent="Account access will activate after Supabase is configured. Use demo mode for now.";return;}const email=$("#email").value,password=$("#password").value;const {data,error}=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(error)$("#auth-error").textContent=error.message;else if(signup&&!data.session)$("#auth-error").textContent="Check your email to confirm your account.";};
  $("#demo-button").onclick=()=>{state.demo=true;state.user={email:"demo@student.local",id:"demo"};localStorage.setItem("igcsemysg_demo","1");loadLocal();showApp();};
  $("#sign-out").onclick=async()=>{if(supabase&&!state.demo)await supabase.auth.signOut();localStorage.removeItem("igcsemysg_demo");state.user=null;state.demo=false;showAuth();};
  $("#nav").onclick=e=>{const b=e.target.closest("button[data-view]");if(!b)return;state.view=b.dataset.view;document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x===b));render();if(innerWidth<701)$(".sidebar").classList.remove("open");};
  $("#board").onchange=e=>{state.board=e.target.value;render();}; $("#subject").onchange=e=>{state.subject=e.target.value;render();}; $("#mobile-menu").onclick=()=>$(".sidebar").classList.toggle("open");
}
async function enter(user){state.user=user;state.demo=false;await loadProgress();showApp();}
function showAuth(){$("#auth-view").classList.remove("hidden");$("#app-view").classList.add("hidden");}
function showApp(){$("#auth-view").classList.add("hidden");$("#app-view").classList.remove("hidden");const name=state.user.email.split("@")[0];$("#user-label").textContent=name;$("#user-initial").textContent=name[0].toUpperCase();$("#demo-notice").classList.toggle("hidden",!state.demo);render();}
function loadLocal(){state.progress=JSON.parse(localStorage.getItem("igcsemysg_progress")||"[]");}
async function loadProgress(){const [{data:progress},{data:preferences},{data:conversation}]=await Promise.all([supabase.from("topic_progress").select("*").eq("user_id",state.user.id),supabase.from("student_preferences").select("*").eq("user_id",state.user.id).maybeSingle(),supabase.from("tutor_conversations").select("id").eq("user_id",state.user.id).order("updated_at",{ascending:false}).limit(1).maybeSingle()]);state.progress=progress||[];state.preferences=preferences||state.preferences;state.conversationId=conversation?.id||null;if(state.conversationId){const {data}=await supabase.from("tutor_messages").select("role,content").eq("conversation_id",state.conversationId).order("created_at").limit(40);state.messages=(data||[]).map(m=>({role:m.role==="assistant"?"ai":"user",text:m.content}));}}
async function saveProgress(topic,score=100){const record={user_id:state.user.id,board:state.board,subject:state.subject,topic,mastery:score,last_studied_at:new Date().toISOString()};state.progress=state.progress.filter(x=>!(x.subject===record.subject&&x.topic===topic));state.progress.push(record);if(state.demo)localStorage.setItem("igcsemysg_progress",JSON.stringify(state.progress));else await supabase.from("topic_progress").upsert(record,{onConflict:"user_id,board,subject,topic"});}
function topics(){return curriculum[state.subject]||defaultTopics;}
function mastery(t){return state.progress.find(x=>x.subject===state.subject&&x.topic===t.title)?.mastery??t.progress;}
function title(k,t,c){return `<div class="page-title"><div><p class="eyebrow">${k}</p><h1>${t}</h1><p>${c}</p></div></div>`;}
function render(){const s=$("#screen");s.className="screen";if(state.view==="learn")s.innerHTML=learn();else if(state.view==="practice")s.innerHTML=practice();else if(state.view==="tutor")s.innerHTML=tutor();else if(state.view==="planner")s.innerHTML=planner();else s.innerHTML=dashboard();wireScreen();}
function dashboard(){const ts=topics(),avg=Math.round(ts.reduce((a,t)=>a+mastery(t),0)/ts.length);return `${title("LEARNING OVERVIEW",`${state.subject} workspace`,`Your progress, priorities and next actions for ${state.board}.`)}<div class="grid metrics"><div class="metric"><span>Overall mastery</span><strong>${avg}%</strong><small>Across ${ts.length} topics</small></div><div class="metric"><span>Topics studied</span><strong>${state.progress.filter(x=>x.subject===state.subject).length}</strong><small>Saved to your profile</small></div><div class="metric"><span>Current priority</span><strong>${ts.sort((a,b)=>mastery(a)-mastery(b))[0].title}</strong><small>Lowest mastery</small></div><div class="metric"><span>Weekly goal</span><strong>3 / 5</strong><small>Learning sessions</small></div></div><div class="grid two"><section class="panel"><h2>Topic mastery</h2>${ts.slice(0,5).map(t=>`<div class="progress-row"><div><b>${t.title}</b><span>${mastery(t)}%</span></div><div class="bar"><i style="width:${mastery(t)}%"></i></div></div>`).join("")}</section><section class="panel"><h2>Recommended next</h2><div class="activity"><i>1</i><div><b>Repair ${ts[0].title}</b><span>12-minute guided lesson</span></div></div><div class="activity"><i>2</i><div><b>Complete adaptive practice</b><span>Questions adjust from your answers</span></div></div><div class="activity"><i>3</i><div><b>Review your error log</b><span>Revisit mistakes after spacing</span></div></div></section></div>`;}
function learn(){return `${title("SYLLABUS LEARNING","Learn by topic","Choose a topic for a concise explanation, worked example and knowledge check.")}<div class="grid topics">${topics().map(t=>`<article class="topic-card"><span class="tag">${t.level.toUpperCase()}</span><h3>${t.title}</h3><p>${t.summary}</p><div class="progress-row"><div><span>Mastery</span><b>${mastery(t)}%</b></div><div class="bar"><i style="width:${mastery(t)}%"></i></div></div><button data-lesson="${t.id}">Open lesson →</button></article>`).join("")}</div>`;}
function lesson(id){const t=topics().find(x=>x.id===id)||topics()[0];return `${title("GUIDED LESSON",t.title,t.summary)}<div class="lesson"><button class="outline" data-back>← All topics</button><section><h2>Understand the idea</h2><p>This lesson connects the definition, method and exam application. Begin by identifying what is known, choose the matching rule, then show each step clearly.</p><div class="formula">Known information → suitable method → checked answer</div></section><section><h2>Worked example</h2><p><b>Question:</b> Explain how you would approach a multi-step ${t.title.toLowerCase()} problem.</p><ol><li>Translate the question into mathematical or scientific information.</li><li>Select the relevant relationship from the syllabus.</li><li>Apply it one step at a time and keep units or notation consistent.</li><li>Check whether the result answers the exact command word.</li></ol><button class="primary" data-complete="${t.title}">Mark lesson complete</button></section></div>`;}
function practice(){const q=questions[Number(sessionStorage.getItem("q")||0)%questions.length];return `${title("ADAPTIVE PRACTICE","One question at a time","Your answer updates mastery and determines what should be practised next.")}<section class="panel question-box"><p class="eyebrow">${q.topic.toUpperCase()}</p><h2>${q.prompt}</h2><div>${q.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${String.fromCharCode(65+i)}. ${c}</button>`).join("")}</div><div id="feedback"></div></section>`;}
function tutor(){return `${title("INTERACTIVE SUPPORT","Ask your personal AI tutor","The tutor remembers this account's learning history, adapts to progress and can compare several AI providers before presenting one clear answer.")}<div class="tutor-layout"><section class="panel chat"><div id="messages" class="messages"><div class="message ai">Tell me the subject, topic or question you are working on. I can explain it step by step or give you a hint.</div>${state.messages.map(m=>`<div class="message ${m.role}">${escapeHtml(m.text)}</div>`).join("")}</div><form id="chat-form" class="composer"><input id="chat-input" required placeholder="Ask about ${state.subject}…"><button>Send</button></form></section><aside class="panel"><h2>Answer mode</h2><label><input id="panel-toggle" type="checkbox" ${state.preferences.multi_model_mode?"checked":""}> Compare OpenAI, Claude and Kimi</label><p class="feedback">Panel mode sends a minimized, anonymous learning context to each configured API, then stores only the synthesized tutor answer. It costs more and may respond more slowly.</p><h2>Useful prompts</h2><button class="choice prompt">Explain this simply</button><button class="choice prompt">Give me a hint, not the answer</button><button class="choice prompt">Test me on my weakest topic</button><button class="choice prompt">Create a 30-minute revision plan</button><p class="feedback">AI may make mistakes. Verify exam-specific guidance against your syllabus and mark scheme.</p></aside></div>`;}
function planner(){const items=["Diagnostic quiz","Weak-topic lesson","Adaptive practice set","Error-log correction","Timed mixed questions"];return `${title("REVISION SYSTEM","Your weekly plan","A repeatable cycle of diagnosis, learning, practice and retrieval.")}<section class="panel">${items.map((x,i)=>`<div class="plan-item ${state.progress.some(p=>p.topic===`plan-${i}`)?"done":""}"><button data-plan="${i}">${state.progress.some(p=>p.topic===`plan-${i}`)?"✓":""}</button><span>${["Monday","Tuesday","Wednesday","Thursday","Saturday"][i]}</span><div><strong>${x}</strong><small>${20+i*10} minutes · ${i<2?"Guided":"Independent"}</small></div></div>`).join("")}</section>`;}
function wireScreen(){document.querySelectorAll("[data-lesson]").forEach(b=>b.onclick=()=>{$("#screen").innerHTML=lesson(b.dataset.lesson);wireScreen();});const back=$("[data-back]");if(back)back.onclick=()=>render();const complete=$("[data-complete]");if(complete)complete.onclick=async()=>{await saveProgress(complete.dataset.complete,100);complete.textContent="Completed ✓";};document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>answerQuestion(b));document.querySelectorAll("[data-plan]").forEach(b=>b.onclick=async()=>{await saveProgress(`plan-${b.dataset.plan}`,100);render();});const form=$("#chat-form");if(form)form.onsubmit=askTutor;const toggle=$("#panel-toggle");if(toggle)toggle.onchange=async()=>{state.preferences.multi_model_mode=toggle.checked;if(!state.demo)await supabase.from("student_preferences").upsert({user_id:state.user.id,multi_model_mode:toggle.checked,provider_consent_at:toggle.checked?new Date().toISOString():null,updated_at:new Date().toISOString()});};document.querySelectorAll(".prompt").forEach(b=>b.onclick=()=>{$("#chat-input").value=b.textContent;});}
async function answerQuestion(button){const idx=Number(button.dataset.choice),qi=Number(sessionStorage.getItem("q")||0)%questions.length,q=questions[qi],correct=idx===q.answer;document.querySelectorAll(".choice[data-choice]").forEach((b,i)=>b.classList.add(i===q.answer?"correct":i===idx?"wrong":""));$("#feedback").innerHTML=`<div class="feedback"><b>${correct?"Correct":"Not quite"}.</b> ${q.why}<br><button class="outline" id="next-q">Next question →</button></div>`;await saveProgress(q.topic,correct?Math.min(100,(state.progress.find(x=>x.topic===q.topic)?.mastery||40)+8):Math.max(10,(state.progress.find(x=>x.topic===q.topic)?.mastery||40)-3));$("#next-q").onclick=()=>{sessionStorage.setItem("q",String(qi+1));render();};}
async function askTutor(e){e.preventDefault();const input=$("#chat-input"),text=input.value.trim();if(!text)return;state.messages.push({role:"user",text});input.value="";render();let reply;if(state.demo||!supabase)reply="Demo response: I would first identify the concept being tested, use your learning history to select the right explanation, compare configured models when panel mode is enabled, and ask you to try the next step.";else{const {data,error}=await supabase.functions.invoke(cfg.tutorFunctionName||"tutor",{body:{message:text,board:state.board,subject:state.subject,conversationId:state.conversationId}});reply=error?`Tutor unavailable: ${error.message}`:data.reply;if(data?.conversationId)state.conversationId=data.conversationId;}state.messages.push({role:"ai",text:reply});render();}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
init();
